WarmBlobByteRangeTask retry from object store on ResourceAlreadyUploadedException (elastic/elasticsearch-serverless#5908)
* WarmBlobByteRangeTask retry from object store on ResourceAlreadyUploadedException

This is an attempt at fixing SharedBlobCacheWarmingServiceIT.testCacheIsWarmedBeforeSearchShardRecovery which would sometimes fail with:
```
org.elasticsearch.ResourceAlreadyUploadedException: [org.elasticsearch.xpack.stateless.cache.reader.MeteringCacheBlobReader@4e09d225] replied that [[term=1, gen=4]] is not found
```

What I believe happens is:
- Search node tries to do offline warming before recover
- It uses `BlobByteRangeWarmer` instead of `WarmingTask` because `searchOfflineWarmingEnabled`
- `BlobByteRangeWarmer` doesn't have the same retry on `ResourceAlreadyUploadedException` as `WarmingTask`
- When index node respond with `ResourceAlreadyUploadedException` the warming task should retry from object store but doesn't
- The warming fails and search shard is left stuck on initializing

The fix is for WarmBlobByteRangeTask to do use the same retry logic as WarmingTask.

Made together with: Cursor