Mock the consumer of old generations for mock StatelessCommitService (elastic/elasticsearch-serverless#903)
Currently, a few tests throw the following exception during the cleanup

```
java.lang.NullPointerException: Cannot invoke "java.util.function.LongConsumer.accept(long)" because "this.closedReadersForGenerationConsumer" is null
	at co.elastic.elasticsearch.stateless.engine.IndexEngine.closedReader(IndexEngine.java:134) ~[classes/:?]
	at co.elastic.elasticsearch.stateless.engine.IndexEngine.lambda$createInternalReaderManager$0(IndexEngine.java:96) ~[classes/:?]
```